### ISSUE TITLE
Error starting sveltekit application with kitql plugin 

### ISSUE THREAD

**Issue by jere2101** [jycouet/kitql#314] opened 2023-01-25 15:02 UTC
### Describe the bug

Hi, 

at the moment i'm testing kitql. And i wanted to add kitql to my current project. The example project is working perfectly fine for me. But when i try to add kitql to my current project or create a new project and then add kitql i get the following error: 

![image](https://user-images.githubusercontent.com/33234850/214596297-5f011c52-64b1-4e2b-bd07-c5126acc8b54.png)

Thank's for your help

### Your Example Website or App

https://github.com/jere2101/svelte-kitql-error-reproduction

### Steps to Reproduce the Bug or Issue

1. npm install
2. npm run dev

### Expected behavior

Starting dev server

### Platform

- OS: Linux
- NodeJS: 16.16.0
- `@kitql/*` version(s): see reproduction

**Comment by jycouet** [comment] 2023-01-25 15:06
Thx for the report, I'll have a look later.

**Comment by jycouet** [comment] 2023-01-26 18:30
The root cause is the graphql version.
You should bump to 16.x.x (I will do a bump of kitql soon)

Then, I noticed that
```
const kitqlConfig = require("./packages/all-in/src/lib/cjs.cjs");
```
should be changed to 
```
const kitqlConfig = require('@kitql/all-in/cjs.cjs');
```

Finally, you have a CSS issue, that you can comment to see the first page.

I don't close the issue as I would like to fix the graphql issue in kitql directly

**Comment by jere2101** [comment] 2023-01-27 07:36
Thank you. These fixes worked for me 🥳

**Closed** 2023-02-23 09:01 UTC
